### ISSUE TITLE
import { StoreModule } from '@nationalbankbelgium/ngrx-store';

### ISSUE THREAD

**Issue by spwizard** [NationalBankBelgium/ngrx-store-ng1#1]
returns error  has no exported member 'StoreModule'.

**Comment by dsebastien** [comment]
Actually you don't need that line; I guess it's a leftover from the original ngrx-store readme file.
Given that this is a port to AngularJS, modules don't exist in the same form as they do in Angular 4.

What exists and matters for NG1 apps is the provider, which allows you to inject the instance of the store where you need it: 
```import { ngrxStoreProviderName, StoreProvider } from "@nationalbankbelgium/ngrx-store/ng1";```

I'll update the readme
